# Generated by Django 5.2.6 on 2025-10-07 06:45

import datetime
import django.core.validators
import django.db.models.deletion
import dose.models.atomic_service
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtomicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Service name (used for registration and lookup)', max_length=100, unique=True)),
                ('python_file', models.FileField(help_text='Python file implementing the atomic service. Must extend AtomicServiceBase.', upload_to='services/', validators=[django.core.validators.FileExtensionValidator(['py'])])),
                ('description', models.TextField(blank=True, help_text='Description of the atomic service')),
                ('config_json', models.JSONField(blank=True, default=dose.models.atomic_service.AtomicService.default_config_json, help_text="JSON parameters for service configuration. Default: {'name': 'value'}", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Atomic Service',
                'verbose_name_plural': 'Atomic Services',
            },
        ),
        migrations.CreateModel(
            name='NavigationPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Panel title (e.g., 'Quick Actions', 'External Systems')", max_length=100)),
                ('panel_type', models.CharField(choices=[('quick_actions', '⚡ Quick Actions - Common tasks and shortcuts'), ('integrations', '🔗 System Integrations - External systems and APIs'), ('analytics', '📊 Analytics & Reports - Data visualization and reporting'), ('workflows', '🔄 Workflows & Automation - Process management'), ('documentation', '📚 Documentation & Help - Knowledge base and guides'), ('administration', '⚙️ Administration - System settings and management'), ('custom', '🎯 Custom Panel - Fully customizable content')], default='custom', help_text='Type of panel for categorization and styling', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Panel description or subtitle')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this panel is visible on the landing page')),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Display order (lower numbers appear first)')),
                ('panel_css_class', models.CharField(blank=True, help_text='Additional CSS classes for custom styling', max_length=100)),
                ('panel_background_color', models.CharField(blank=True, help_text='Hex color code for panel background (e.g., #f0f8ff)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Navigation Panel',
                'verbose_name_plural': 'Navigation Panels',
            },
        ),
        migrations.CreateModel(
            name='PassThroughEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable or disable passthrough for this endpoint')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('google', 'Google'), ('facebook', 'Facebook'), ('custom', 'Custom')], default='custom', help_text='OAuth2 provider or passthrough method', max_length=20)),
                ('endpoint_url', models.URLField(help_text='External endpoint URL for this tenant', max_length=300)),
                ('description', models.CharField(blank=True, default='', help_text='Description or purpose of this endpoint', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_path', models.CharField(blank=True, default='', help_text='Only requests matching this path will be passed through to the target', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(blank=True, default='#007bff', help_text="Primary color for this tenant's admin theme (e.g., #007bff)", max_length=20)),
                ('name', models.CharField(help_text='Tenant organization name', max_length=100)),
                ('slug', models.SlugField(default='default', help_text='Unique identifier for the tenant')),
                ('schema_name', models.CharField(blank=True, help_text='PostgreSQL schema name for this tenant (auto-generated from slug)', max_length=63, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Tenant description or details')),
                ('tagline', models.CharField(blank=True, default='', help_text='Tenant tagline or slogan', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Tenant logo image', null=True, upload_to='tenant_logos/')),
                ('created_at', models.DateTimeField(blank=True, help_text='When this tenant was created', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
        migrations.CreateModel(
            name='DeepSeekPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='Prompt sent to DeepSeek API')),
                ('response', models.TextField(blank=True, help_text='Response from DeepSeek API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deepseek_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DoseAI Prompt',
                'verbose_name_plural': 'DoseAI Prompts',
            },
        ),
        migrations.CreateModel(
            name='DoseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Link title/label (e.g., 'Customer Portal', 'Generate Report')", max_length=100)),
                ('item_type', models.CharField(choices=[('link', '🔗 External Link - URL to external system'), ('internal', '🏠 Internal Page - Django view or URL pattern'), ('api', '🌐 API Endpoint - Direct API call or integration'), ('modal', '🪟 Modal Content - Pop-up dialog or form'), ('download', '📥 File Download - Document or resource download'), ('mailto', '📧 Email Link - Open email client'), ('tel', '📞 Phone Link - Trigger phone call'), ('custom', '⚡ Custom Action - JavaScript or special behavior')], default='link', help_text='Type of navigation item', max_length=20)),
                ('url', models.CharField(help_text='URL, endpoint, or action target', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Item description or tooltip text')),
                ('icon_style', models.CharField(choices=[('emoji', '😊 Emoji Icons'), ('fontawesome', '🎨 Font Awesome'), ('bootstrap', '🅱️ Bootstrap Icons'), ('custom', '🖼️ Custom Image'), ('none', '⭕ No Icon')], default='emoji', help_text='Icon display style', max_length=20)),
                ('icon_value', models.CharField(blank=True, help_text='Icon value (emoji, FA class, image URL, etc.)', max_length=100)),
                ('target', models.CharField(choices=[('_self', 'Same Window/Tab'), ('_blank', 'New Window/Tab'), ('_parent', 'Parent Frame'), ('modal', 'Modal Dialog'), ('iframe', 'Embedded Frame')], default='_self', help_text='How the link should open', max_length=10)),
                ('requires_authentication', models.BooleanField(default=True, help_text='Whether user must be logged in to access this item')),
                ('requires_permissions', models.CharField(blank=True, help_text="Comma-separated list of required permissions (e.g., 'dose.view_task,dose.add_instruction')", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is visible and clickable')),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Display order within the panel (lower numbers appear first)')),
                ('item_css_class', models.CharField(blank=True, help_text='Additional CSS classes for custom styling', max_length=100)),
                ('button_color', models.CharField(blank=True, help_text='Hex color code for button/link color (e.g., #007bff)', max_length=7)),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Number of times this item has been clicked')),
                ('last_clicked', models.DateTimeField(blank=True, help_text='When this item was last clicked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('panel', models.ForeignKey(help_text='Panel this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='dose.navigationpanel')),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('matchingEventKey', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parameters_json', models.JSONField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to (for multi-tenant data isolation)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=128, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=128, null=True)),
                ('card_name', models.CharField(blank=True, help_text='Name on card', max_length=128, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dose.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('body', models.JSONField(blank=True, help_text='Request body/payload as JSON', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to (for multi-tenant data isolation)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant')),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
            },
        ),
        migrations.AddField(
            model_name='navigationpanel',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to (for multi-tenant data isolation)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.CreateModel(
            name='MLTaxonomy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('matchingEventKey', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(default='Description', max_length=255)),
                ('content_json', models.JSONField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to (for multi-tenant data isolation)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MLEngine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('engineName', models.CharField(max_length=100)),
                ('engineEndPoint', models.CharField(max_length=100)),
                ('matchingEventKey', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(default='Description', max_length=255)),
                ('parameters_json', models.JSONField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to (for multi-tenant data isolation)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MLDataset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('matchingEventKey', models.CharField(blank=True, max_length=100, null=True)),
                ('isTraining', models.BooleanField(default=True)),
                ('description', models.CharField(default='Description', max_length=255)),
                ('content_json', models.JSONField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to (for multi-tenant data isolation)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('eventKey', models.CharField(blank=True, max_length=100, null=True)),
                ('requestpath', models.CharField(max_length=200)),
                ('requestmethod', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('EVAL', 'EVAL')], default='GET', max_length=6)),
                ('direction', models.CharField(choices=[('REQ', 'REQUEST'), ('RES', 'RESPONSE')], default='REQ', max_length=3)),
                ('urllist', models.CharField(blank=True, default='', help_text='The urllist can be a local or remote URL with the full path. If specifying more than one, separate multiple URLs with a comma.', max_length=200, null=True)),
                ('appusername', models.CharField(default='appusername', max_length=200)),
                ('executescript', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.CharField(default='Description', max_length=255)),
                ('parameters_json', models.JSONField(blank=True, null=True)),
                ('save_callbackdata', models.BooleanField(default=False, help_text='If true, save response content to callbackdata.')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to (for multi-tenant data isolation)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant')),
            ],
            options={
                'verbose_name': 'Instruction',
                'verbose_name_plural': 'Instructions',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to (for multi-tenant data isolation)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant')),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
            },
        ),
        migrations.CreateModel(
            name='DashboardButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Button title/label (e.g., 'Customer Portal', 'Generate Report')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Button description or subtitle')),
                ('url', models.CharField(help_text='URL, endpoint, or action target', max_length=500)),
                ('button_type', models.CharField(choices=[('link', '🔗 External Link - URL to external system'), ('internal', '🏠 Internal Page - Django view or URL pattern'), ('api', '🌐 API Endpoint - Direct API call or integration'), ('modal', '🪟 Modal Content - Pop-up dialog or form'), ('download', '📥 File Download - Document or resource download'), ('mailto', '📧 Email Link - Open email client'), ('tel', '📞 Phone Link - Trigger phone call'), ('custom', '⚡ Custom Action - JavaScript or special behavior')], default='link', help_text='Type of button action', max_length=20)),
                ('icon_style', models.CharField(choices=[('emoji', '😊 Emoji Icons'), ('fontawesome', '🎨 Font Awesome'), ('bootstrap', '🅱️ Bootstrap Icons'), ('custom', '🖼️ Custom Image'), ('none', '⭕ No Icon')], default='emoji', help_text='Icon display style', max_length=20)),
                ('icon_value', models.CharField(blank=True, help_text='Icon value (emoji, FA class, image URL, etc.)', max_length=100)),
                ('target', models.CharField(choices=[('_self', 'Same Window/Tab'), ('_blank', 'New Window/Tab'), ('_parent', 'Parent Frame'), ('modal', 'Modal Dialog'), ('iframe', 'Embedded Frame')], default='_self', help_text='How the link should open', max_length=10)),
                ('color', models.CharField(blank=True, help_text='Button color (CSS color or hex code, e.g., #007bff, blue, var(--dose-primary))', max_length=50)),
                ('size', models.CharField(choices=[('small', 'Small Button (1 grid unit)'), ('medium', 'Medium Button (2 grid units)'), ('large', 'Large Button (3 grid units)'), ('full', 'Full Width Button (spans entire row)')], default='medium', help_text='Button size on the dashboard', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this button is visible on the dashboard')),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Display order (lower numbers appear first)')),
                ('button_css_class', models.CharField(blank=True, help_text='Additional CSS classes for custom styling', max_length=100)),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Number of times this button has been clicked')),
                ('last_clicked', models.DateTimeField(blank=True, help_text='When this button was last clicked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this dashboard button', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to (for multi-tenant data isolation)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant')),
            ],
            options={
                'verbose_name': 'Dashboard Button',
                'verbose_name_plural': 'Dashboard Buttons',
            },
        ),
        migrations.CreateModel(
            name='CallBackData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('matchingEventKey', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(default='Description', max_length=255)),
                ('parameters_json', models.JSONField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('callbackdata', models.JSONField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to (for multi-tenant data isolation)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant')),
            ],
            options={
                'verbose_name': 'Call Back Data',
                'verbose_name_plural': 'Call Back Data',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_theme', models.CharField(default='flatly', max_length=50)),
                ('dark_theme', models.CharField(default='darkly', max_length=50)),
                ('use_system_pref', models.BooleanField(default=False)),
                ('last_selected_theme', models.CharField(default='flatly', max_length=50)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dose.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IgnorePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text="URL path pattern to ignore (e.g., '/admin/', '/api/v1/*', '*.css')", max_length=500)),
                ('description', models.CharField(blank=True, help_text='Description of what this path is used for', max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Additional parameters or configuration in JSON format')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this ignore path is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to (for multi-tenant data isolation)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant')),
            ],
            options={
                'verbose_name': 'Ignore Path',
                'verbose_name_plural': 'Ignore Paths',
                'ordering': ['url'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='dose_ignore_tenant__94314f_idx'), models.Index(fields=['url'], name='dose_ignore_url_05e7f0_idx')],
            },
        ),
    ]
