# Generated by Django 5.2.6 on 2025-10-07 08:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(default='flatly', help_text="Jazzmin/Bootswatch theme name (e.g., 'flatly', 'cyborg', 'darkly')", max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dark_theme',
            field=models.CharField(default='darkly', help_text='Preferred dark theme', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_selected_theme',
            field=models.CharField(default='flatly', help_text='Last selected theme (light or dark)', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='light_theme',
            field=models.CharField(default='flatly', help_text='Preferred light theme', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='use_system_pref',
            field=models.BooleanField(default=False, help_text='Use system preference for light/dark mode'),
        ),
    ]
