# Generated by Django 5.2.6 on 2025-10-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0002_alter_userprofile_options_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passthroughendpoint',
            name='menu_icon',
            field=models.CharField(blank=True, default='🔗', help_text='Icon to display in the menu (emoji, Font Awesome class, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='passthroughendpoint',
            name='menu_sort_order',
            field=models.PositiveIntegerField(default=100, help_text='Sort order for menu display (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='passthroughendpoint',
            name='menu_title',
            field=models.CharField(blank=True, help_text='Title to display in the menu (defaults to extracted title from description or URL)', max_length=100),
        ),
        migrations.AddField(
            model_name='passthroughendpoint',
            name='show_in_menu',
            field=models.BooleanField(default=True, help_text='Show this passthrough endpoint as a menu item in the top navigation'),
        ),
    ]
