# Generated by Django 5.2.6 on 2025-10-17 04:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0003_add_passthrough_menu_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Request path (e.g., /admin/dashboard/)', max_length=500)),
                ('method', models.CharField(default='GET', help_text='HTTP method', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_agent', models.CharField(blank=True, help_text='Browser/client info', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='dose_userre_user_id_6467c0_idx'), models.Index(fields=['path'], name='dose_userre_path_2ef58e_idx')],
            },
        ),
    ]
