# Generated by Django 5.2.6 on 2025-10-17 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0004_userrequesttracker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userrequesttracker',
            name='dose_userre_user_id_6467c0_idx',
        ),
        migrations.AddField(
            model_name='userrequesttracker',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to='dose.tenant'),
        ),
        migrations.AddIndex(
            model_name='userrequesttracker',
            index=models.Index(fields=['user', 'tenant', '-timestamp'], name='dose_userre_user_id_4074f9_idx'),
        ),
        migrations.AddIndex(
            model_name='userrequesttracker',
            index=models.Index(fields=['tenant', '-timestamp'], name='dose_userre_tenant__ccd44e_idx'),
        ),
    ]
