# Generated by Django 5.2.7 on 2025-10-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0005_remove_userrequesttracker_dose_userre_user_id_6467c0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passthroughendpoint',
            name='trigger_path_length',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
