# Generated by Django 5.2.7 on 2025-10-31 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0007_add_detected_url_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passthroughendpoint',
            name='trigger_path_length',
        ),
    ]
