# Generated by Django 5.2.7 on 2025-11-09 00:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0009_add_navigation_user_scoping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationitem',
            options={'ordering': ['panel', 'sort_order', 'title'], 'verbose_name': 'Navigation Item', 'verbose_name_plural': 'Navigation Items'},
        ),
        migrations.RemoveField(
            model_name='passthroughendpoint',
            name='detected_base_url',
        ),
        migrations.RemoveField(
            model_name='passthroughendpoint',
            name='detected_subpaths',
        ),
        migrations.AddField(
            model_name='passthroughendpoint',
            name='bypass_middleware',
            field=models.BooleanField(default=False, help_text='If True, this trigger_path will NOT be processed by passthrough middleware (use for dedicated views like Gmail/OSTicket that handle their own routing)'),
        ),
        migrations.AddField(
            model_name='passthroughendpoint',
            name='passthrough_type',
            field=models.CharField(choices=[('api', 'API - REST/GraphQL endpoints (e.g., Gmail API)'), ('scraper', 'Scraper - HTML screen scraping (e.g., OSTicket)')], default='scraper', help_text="Type of passthrough: 'api' for REST APIs (Gmail), 'scraper' for HTML content (OSTicket)", max_length=20),
        ),
        migrations.AddIndex(
            model_name='navigationitem',
            index=models.Index(fields=['panel', 'is_active', 'sort_order'], name='dose_naviga_panel_i_63e13c_idx'),
        ),
        migrations.AddIndex(
            model_name='navigationitem',
            index=models.Index(fields=['item_type', 'is_active'], name='dose_naviga_item_ty_e928df_idx'),
        ),
    ]
