# Generated by Django 5.2.7 on 2025-11-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0010_add_passthrough_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationitem',
            options={'verbose_name': 'Navigation Item', 'verbose_name_plural': 'Navigation Items'},
        ),
        migrations.RemoveIndex(
            model_name='navigationitem',
            name='dose_naviga_panel_i_63e13c_idx',
        ),
        migrations.RemoveIndex(
            model_name='navigationitem',
            name='dose_naviga_item_ty_e928df_idx',
        ),
        migrations.RemoveField(
            model_name='navigationitem',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='navigationitem',
            name='is_personal',
        ),
        migrations.RunSQL(
            # BUG (historical): forward SQL was noop; state had the field but DB often did not.
            # Real DDL: dose.0027_passthroughendpoint_discovered_subpaths_ddl
            sql=migrations.RunSQL.noop,
            # Reverse: No-op
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AddField(
                    model_name='passthroughendpoint',
                    name='discovered_subpaths',
                    field=models.JSONField(blank=True, default=dict, help_text='Auto-discovered subpaths for this endpoint'),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='target',
            field=models.CharField(choices=[('_self', 'Same Window/Tab'), ('_blank', 'New Window/Tab'), ('_parent', 'Parent Frame'), ('modal', 'Modal Dialog'), ('iframe', 'Embedded Frame')], default='_self', help_text='How the link should open', max_length=10),
        ),
    ]
