# Generated by Django 5.2.7 on 2025-11-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0011_add_discovered_subpaths_to_passthroughendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='passthroughendpoint',
            name='api_auth_type',
            field=models.CharField(choices=[('bearer', 'Bearer Token'), ('basic', 'Basic Auth (base64)'), ('api_key', 'API Key (custom header)'), ('oauth2', 'OAuth2')], default='bearer', help_text='API authentication method', max_length=20),
        ),
        migrations.AddField(
            model_name='passthroughendpoint',
            name='api_endpoint',
            field=models.URLField(blank=True, default='', help_text='API base URL (e.g., https://www.googleapis.com/gmail/v1) - required for web_api and api_only modes', max_length=300),
        ),
        migrations.AddField(
            model_name='passthroughendpoint',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='API key or token (encrypted storage recommended for production)', max_length=500),
        ),
        migrations.AddField(
            model_name='passthroughendpoint',
            name='api_key_header',
            field=models.CharField(blank=True, default='Authorization', help_text="Header name for API key (e.g., 'Authorization', 'X-API-Key')", max_length=100),
        ),
        migrations.AddField(
            model_name='passthroughendpoint',
            name='integration_mode',
            field=models.CharField(choices=[('web_only', 'Web UI Only - No API (e.g., OSTicket)'), ('web_api', 'Web UI + API - Both available (e.g., Gmail)'), ('api_only', 'API Only - Custom Dose UI via atomic services')], default='web_only', help_text='How this service integrates: web UI only, web UI + API, or API only', max_length=20),
        ),
    ]
