# Generated by Django 5.2.7 on 2025-11-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0012_passthroughendpoint_api_auth_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passthroughendpoint',
            name='auth_password',
            field=models.CharField(blank=True, default='', help_text='Password for auto-login (encrypted storage recommended). NOTE: For demo only - future use OAuth2', max_length=500),
        ),
        migrations.AddField(
            model_name='passthroughendpoint',
            name='auth_username',
            field=models.CharField(blank=True, default='', help_text='Username for auto-login (e.g., Odoo email). NOTE: For demo only - future use OAuth2 for multi-user support', max_length=200),
        ),
    ]
