# Generated by Django 5.2.7 on 2025-11-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0013_passthroughendpoint_auth_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passthroughendpoint',
            name='inject_proxy_script',
            field=models.BooleanField(default=False, help_text='If True, inject PolySaaS API interceptor script to capture XHR/Fetch calls from SPAs (e.g., Airtable, Notion)'),
        ),
    ]
