# Generated by Django 5.2.7 on 2025-11-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0015_trafficlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='passthroughendpoint',
            name='polysniffer_debug_output',
            field=models.TextField(blank=True, default='', help_text='PolySniffer debug output - captured HTTP traffic and analysis for this endpoint'),
        ),
        migrations.AddField(
            model_name='passthroughendpoint',
            name='polysniffer_last_run',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last PolySniffer run', null=True),
        ),
    ]
