# Generated by Django 5.2.7 on 2025-11-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0017_add_mq_input_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='passthroughendpoint',
            name='handler_class',
            field=models.CharField(blank=True, default='', help_text="Handler class name (e.g., 'V0PassthroughHandler', 'DefaultScraperHandler'). Auto-generated on first access if empty. AI can update this based on PolySniffer captures.", max_length=200),
        ),
        migrations.AddField(
            model_name='passthroughendpoint',
            name='handler_code',
            field=models.TextField(blank=True, default='', help_text='Custom handler code (Python) - generated by AI based on PolySniffer captures. If set, this code is used instead of registered handlers.'),
        ),
    ]
