# Generated by Django 5.2.7 on 2025-12-03 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0018_add_handler_fields_to_passthrough_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passthroughendpoint',
            name='handler_class',
        ),
        migrations.RemoveField(
            model_name='passthroughendpoint',
            name='handler_code',
        ),
        migrations.RemoveField(
            model_name='passthroughendpoint',
            name='polysniffer_debug_output',
        ),
        migrations.RemoveField(
            model_name='passthroughendpoint',
            name='polysniffer_last_run',
        ),
    ]
