# Generated by Django 5.2.7 on 2025-12-03 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0019_remove_passthroughendpoint_handler_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolySnifferRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('packets_captured', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('raw_data_summary', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to (for multi-tenant data isolation)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant')),
            ],
            options={
                'verbose_name': 'PolySniffer Run',
                'verbose_name_plural': 'PolySniffer Runs',
                'ordering': ['-run_timestamp'],
            },
        ),
    ]
