# Generated by Django 5.2.7 on 2026-01-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0020_polysnifferrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passthroughendpoint',
            name='endpoint_url',
            field=models.URLField(help_text='Full URL to any page inside the service (e.g. http://osticket.polysaas.online/scp/login.php)', max_length=300),
        ),
        migrations.AlterField(
            model_name='passthroughendpoint',
            name='trigger_path',
            field=models.CharField(blank=True, default='', help_text='One word, no slashes please', max_length=200, verbose_name='Trigger Word'),
        ),
    ]
