# Generated by Django 6.0.2 on 2026-03-07 09:10
# Edited: removed oauth2_provider dependency and oauth_application field so migration
# loads when django-oauth-toolkit is not installed. oauth_application is added in 0023.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0021_alter_passthroughendpoint_endpoint_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('mattermost', 'Mattermost'), ('odoo', 'Odoo'), ('nextcloud', 'Nextcloud'), ('liferay', 'Liferay'), ('polysysmon', 'PolySysMon')], max_length=50)),
                ('app_url', models.URLField(blank=True, default='')),
                ('provisioned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('error', 'Error'), ('disabled', 'Disabled')], default='provisioning', max_length=20)),
                ('last_error', models.TextField(blank=True, default='', help_text='Last provisioning error message')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='dose.tenant')),
            ],
            options={
                'verbose_name': 'Tenant App',
                'verbose_name_plural': 'Tenant Apps',
                'unique_together': {('tenant', 'app_name')},
            },
        ),
    ]
