# Generated by Django 5.2.7 on 2026-03-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0022_tenantapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan_tier',
            field=models.CharField(choices=[('starter', 'Starter (1 user)'), ('team', 'Team (3 users)'), ('unlimited', 'Unlimited')], default='starter', max_length=20),
        ),
        migrations.AlterField(
            model_name='passthroughendpoint',
            name='bypass_middleware',
            field=models.BooleanField(default=False, help_text='If True, this trigger_path will NOT be processed by passthrough middleware (use for dedicated views like Gmail that handle their own routing)'),
        ),
        migrations.AlterField(
            model_name='passthroughendpoint',
            name='endpoint_url',
            field=models.URLField(help_text='Full URL to any page inside the service (e.g. http://nextcloud.polysaas.online)', max_length=300),
        ),
        migrations.AlterField(
            model_name='passthroughendpoint',
            name='integration_mode',
            field=models.CharField(choices=[('web_only', 'Web UI Only - No API'), ('web_api', 'Web UI + API - Both available (e.g., Gmail)'), ('api_only', 'API Only - Custom Dose UI via atomic services')], default='web_only', help_text='How this service integrates: web UI only, web UI + API, or API only', max_length=20),
        ),
        migrations.AlterField(
            model_name='passthroughendpoint',
            name='passthrough_type',
            field=models.CharField(choices=[('api', 'API - REST/GraphQL endpoints (e.g., Gmail API)'), ('scraper', 'Scraper - HTML screen scraping (e.g., Nextcloud)')], default='scraper', help_text="Type of passthrough: 'api' for REST APIs (Gmail), 'scraper' for HTML content", max_length=20),
        ),
    ]
