# Generated by Django 5.2.11 on 2026-03-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0023_add_plan_tier_to_subscription'),
        ('dose', '0023_tenantapp_oauth_application_optional'),
    ]

    operations = [
    ]
