# Generated by Django 5.2.7 on 2026-03-21 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0024_merge_20260321_1554'),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable name e.g. 'Dolibarr Thirdparty -> Normalized Customer'", max_length=200)),
                ('slug', models.SlugField(help_text='Used in instruction references', max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('direction', models.CharField(choices=[('SOURCE_TO_NORMALIZED', 'Source -> Normalized'), ('NORMALIZED_TO_TARGET', 'Normalized -> Target')], default='SOURCE_TO_NORMALIZED', max_length=25)),
                ('field_mappings', models.JSONField(default=dict, help_text='Dict of {target_field: source_expression}. Expressions: \'request.POST.name|strip\', \'payload.email|lower|default:None\', \'lookup:country_code->iso2\', \'now:iso\', "\'literal\'"')),
                ('transformations', models.JSONField(blank=True, default=list, help_text='List of post-mapping rules. [{\'field\': \'full_address\', \'expression\': \'address + ", " + zip + " " + town\'}]')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_endpoint', models.ForeignKey(blank=True, help_text='Optional: source system (e.g. Dolibarr passthrough)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_mappings', to='dose.passthroughendpoint')),
                ('target_endpoint', models.ForeignKey(blank=True, help_text='Optional: target system (e.g. Odoo XML-RPC)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_mappings', to='dose.passthroughendpoint')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to (for multi-tenant data isolation)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant')),
            ],
            options={
                'verbose_name': 'Mapping',
                'verbose_name_plural': 'Mappings',
                'ordering': ['name'],
                'unique_together': {('slug', 'direction')},
            },
        ),
        migrations.CreateModel(
            name='InstructionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Execution order when multiple mappings are attached')),
                ('enabled', models.BooleanField(default=True)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='dose.instruction')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dose.mapping')),
            ],
            options={
                'verbose_name': 'Instruction Mapping',
                'verbose_name_plural': 'Instruction Mappings',
                'ordering': ['order'],
                'unique_together': {('instruction', 'mapping')},
            },
        ),
    ]
