# Generated by Django 5.2.11 on 2026-03-24 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0024_merge_20260325_0635'),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='tenantapp',
                    name='oauth_application',
                    field=models.OneToOneField(blank=True, help_text='The OAuth2 application registered in DOT for this tenant+app pair', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_app', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
                ),
            ],
        ),
    ]
