# Generated by Django 5.2.11 on 2026-03-24 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0027_passthroughendpoint_discovered_subpaths_ddl'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPrompt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Stable identifier for code or orchestration (unique per tenant).', max_length=150)),
                ('description', models.CharField(default='Description', max_length=255)),
                ('prompt_text', models.TextField(help_text='Full prompt body.')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this record belongs to (for multi-tenant data isolation)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant')),
            ],
            options={
                'verbose_name': 'ML prompt',
                'verbose_name_plural': 'ML prompts',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='dose_mlprompt_unique_tenant_key')],
            },
        ),
    ]
