# Generated by Django 5.2.7 on 2026-03-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0025_add_mapping_and_instruction_mapping'),
        ('dose', '0028_mlprompt'),
    ]

    operations = [
    ]
