# Generated by Django 5.2.7 on 2026-03-31 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0030_user_tenant_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_tier',
            field=models.CharField(choices=[('polysaas-1', 'PolySaaS-1 (1 app)'), ('polysaas-3', 'PolySaaS-3 (3 apps)'), ('polysaas-unlimited', 'PolySaaS-Unlimited')], default='polysaas-1', max_length=30),
        ),
        migrations.AddIndex(
            model_name='usertenantmembership',
            index=models.Index(fields=['user', 'tenant'], name='user_tenant_user_id_47ab36_idx'),
        ),
        migrations.AddIndex(
            model_name='usertenantmembership',
            index=models.Index(fields=['tenant', 'role'], name='user_tenant_tenant__76e3c3_idx'),
        ),
    ]
