# Generated by Django 6.0.2 on 2026-04-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0031_rename_plan_tiers_to_polysaas'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='selected_apps',
            field=models.JSONField(blank=True, default=list, help_text='App keys selected at subscribe time'),
        ),
        migrations.AlterField(
            model_name='tenantapp',
            name='app_name',
            field=models.CharField(choices=[('mattermost', 'Mattermost'), ('odoo', 'Odoo'), ('nextcloud', 'Nextcloud'), ('dolibarr', 'Dolibarr'), ('wordpress', 'WordPress'), ('liferay', 'Liferay'), ('monitor_logger', 'Monitor Logger'), ('polysysmon', 'PolySysMon')], max_length=50),
        ),
    ]
