# Generated by Django 5.2.7 on 2026-04-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0032_add_selected_apps_to_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantapp',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict, help_text='App-specific config (tokens, team IDs, etc.)'),
        ),
    ]
