# Generated by Django 5.2.11 on 2026-04-24 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0035_passthroughendpoint_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficlog',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='ignorepath',
            new_name='dose_ignore_tenant__7bd19b_idx',
            old_name='dose_ignore_tenant__94314f_idx',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='id',
        ),
        migrations.AlterField(
            model_name='callbackdata',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='dashboardbutton',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='ignorepath',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='mldataset',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='mlengine',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='mlprompt',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='mltaxonomy',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='mqconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='mqinput',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='mqoutput',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='navigationpanel',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='passthroughendpoint',
            name='passthrough_stream_debug',
            field=models.BooleanField(default=False, help_text='If True, log passthrough stream diagnostics (upstream + final HTML snippets, asset URLs, Set-Cookie samples) to the server console. Or set POLYSNIFFER_PASSTHROUGH_DEBUG in settings for all endpoints.'),
        ),
        migrations.AlterField(
            model_name='polysnifferrun',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(default='default', help_text='Unique identifier for the tenant (primary key)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_slug', on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
        migrations.DeleteModel(
            name='TrafficLog',
        ),
    ]
