# Generated by Django 5.2.11 on 2026-04-25 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0038_alter_usertenantmembership_tenant_id_to_varchar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_slug', help_text='Tenant this record belongs to (for multi-tenant data isolation, FK to slug)', null=True, on_delete=django.db.models.deletion.CASCADE, to='dose.tenant'),
        ),
    ]
