# Generated by Django 5.2.11 on 2026-04-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0042_alter_dashboardbutton_tenant_fk_column_to_varchar'),
    ]

    operations = [
        migrations.AddField(
            model_name='passthroughendpoint',
            name='starting_uri',
            field=models.CharField(blank=True, default='', help_text='Starting URI path for this endpoint (e.g., /web for Odoo, / for Mattermost)', max_length=500),
        ),
    ]
