# Generated by Django 5.2.11 on 2026-05-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0045_alter_userrequesttracker_tenant_id_to_varchar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(help_text='e.g. odoo, nextcloud, dolibarr', max_length=50, unique=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, help_text='Optional direct login URL')),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['app_name'],
            },
        ),
        migrations.AlterField(
            model_name='passthroughendpoint',
            name='api_endpoint',
            field=models.CharField(blank=True, default='', help_text='API base URL for programmatic access (e.g., https://api.gmail.com/v1 or http://service-name:port)', max_length=300),
        ),
        migrations.AlterField(
            model_name='passthroughendpoint',
            name='endpoint_url',
            field=models.CharField(help_text='Full URL to any page inside the service (e.g. http://nextcloud.polysaas.online or http://service-name:80 for internal Docker)', max_length=300),
        ),
    ]
