# Generated by Django 5.2.11 on 2026-05-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0046_appcredential_alter_passthroughendpoint_api_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='match_extra',
            field=models.JSONField(blank=True, default=dict, help_text='Extra conditions, e.g. {"method": "GET"} to restrict HTTP method'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='match_type',
            field=models.CharField(choices=[('path', 'URL Path Contains'), ('action_id', 'Odoo Action ID (e.g. account.action_invoice)'), ('menu_id', 'Odoo Menu ID (numeric)'), ('regex', 'Regex on full URL'), ('contains', 'Contains string (anywhere in URL)')], default='path', help_text='How to interpret requestpath when matching incoming upstream URLs', max_length=20),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='requestpath',
            field=models.CharField(help_text='Match value: path fragment, action_id, menu_id number, regex, or substring — interpreted by match_type', max_length=500),
        ),
    ]
