# Generated by Django 5.2.11 on 2026-05-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0048_remove_passthroughendpoint_trigger_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bold_text',
            field=models.BooleanField(default=False, help_text='Enable bold text for better readability'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='font_size',
            field=models.CharField(default='medium', help_text='Font size: small, medium, large', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='high_contrast',
            field=models.BooleanField(default=False, help_text='Enable high contrast mode'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reduce_motion',
            field=models.BooleanField(default=False, help_text='Reduce animations and motion'),
        ),
        migrations.AlterField(
            model_name='passthroughendpoint',
            name='bypass_middleware',
            field=models.BooleanField(default=False, help_text='If True, this endpoint will NOT be processed by passthrough middleware (use for dedicated views like Gmail that handle their own routing)'),
        ),
        migrations.AlterField(
            model_name='passthroughendpoint',
            name='slug',
            field=models.CharField(blank=True, default='', help_text='Optional identifier for non–passthrough features (menus, links, other Django code). Leave blank if unused.', max_length=100),
        ),
    ]
