# Generated by Django 5.2.11 on 2026-05-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0048_remove_passthroughendpoint_trigger_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passthroughendpoint',
            name='bypass_middleware',
            field=models.BooleanField(default=False, help_text='If True, this endpoint will NOT be processed by passthrough middleware (use for dedicated views like Gmail that handle their own routing)'),
        ),
        migrations.AlterField(
            model_name='passthroughendpoint',
            name='slug',
            field=models.CharField(blank=True, default='', help_text='Optional identifier for non–passthrough features (menus, links, other Django code). Leave blank if unused.', max_length=100),
        ),
    ]
