# Generated by Django 5.2.11 on 2026-05-22 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0049_add_display_settings_to_userprofile'),
        ('dose', '0049_alter_passthroughendpoint_bypass_middleware_and_more'),
    ]

    operations = [
    ]
