# Generated by Django 5.2.11 on 2026-08-20 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0060_alter_passthroughendpoint_endpoint_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passthroughendpoint',
            name='endpoint_url',
            field=models.CharField(help_text='Full URL to any page inside the service (e.g. http://nextcloud.polysaas.online or http://service-name:80 for internal Docker)', max_length=300),
        ),
        migrations.AlterField(
            model_name='tenantapp',
            name='app_name',
            field=models.CharField(choices=[('mattermost', 'Mattermost'), ('odoo', 'Odoo'), ('nextcloud', 'Nextcloud'), ('dolibarr', 'Dolibarr'), ('wordpress', 'WordPress'), ('liferay', 'Liferay'), ('monitor_logger', 'Monitor Logger'), ('polysysmon', 'PolySysMon'), ('hubspot', 'HubSpot'), ('slack', 'Slack')], max_length=50),
        ),
        migrations.CreateModel(
            name='WebhookMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='Stable hash for deduplication (tenant-scoped)', max_length=64)),
                ('correlation_id', models.UUIDField(help_text='UUID for tracing across systems')),
                ('envelope', models.JSONField(help_text='Full canonical trigger envelope (polysaas.trigger.v1)')),
                ('action_path', models.CharField(db_index=True, help_text='Action path from envelope for quick filtering', max_length=500)),
                ('source', models.CharField(db_index=True, help_text='Source system: slack, hubspot, etc', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('processed', 'Processed'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='TTL - mailbox entry expires if not processed by this time')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='', help_text='Error message if status=failed')),
                ('result', models.JSONField(blank=True, help_text='Processing result from consumer', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dose.tenant')),
            ],
            options={
                'db_table': 'webhook_mailbox',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'expires_at'], name='mailbox_consumer_idx'), models.Index(fields=['status', 'created_at'], name='mailbox_status_idx')],
                'unique_together': {('tenant', 'event_id')},
            },
        ),
    ]
