# Generated by Django 5.2.11 on 2026-04-12 01:29

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dose', '0035_passthroughendpoint_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLDatasetProxy',
            fields=[
            ],
            options={
                'verbose_name': 'ML Dataset',
                'verbose_name_plural': 'ML Datasets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dose.mldataset',),
        ),
        migrations.CreateModel(
            name='MLEngineProxy',
            fields=[
            ],
            options={
                'verbose_name': 'ML Engine',
                'verbose_name_plural': 'ML Engines',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dose.mlengine',),
        ),
        migrations.CreateModel(
            name='MLPromptProxy',
            fields=[
            ],
            options={
                'verbose_name': 'ML Prompt',
                'verbose_name_plural': 'ML Prompts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dose.deepseekprompt',),
        ),
        migrations.CreateModel(
            name='MLTaxonomyProxy',
            fields=[
            ],
            options={
                'verbose_name': 'ML Taxonomy',
                'verbose_name_plural': 'ML Taxonomies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dose.mltaxonomy',),
        ),
    ]
