# Generated by Django 5.2.4 on 2025-08-06 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('matchingKey', models.CharField(help_text='Unique identifier for this parameter set', max_length=200)),
                ('sequence', models.IntegerField(default=1, help_text='Order sequence for parameter execution')),
                ('param_kwargs_json', models.JSONField(blank=True, help_text='JSON data for additional parameters', null=True)),
                ('param1', models.CharField(blank=True, default='N/A', max_length=200, null=True)),
                ('param2', models.CharField(blank=True, default='N/A', max_length=200, null=True)),
                ('param3', models.CharField(blank=True, default='N/A', max_length=200, null=True)),
                ('param4', models.CharField(blank=True, default='N/A', max_length=200, null=True)),
                ('param5', models.CharField(blank=True, default='N/A', max_length=200, null=True)),
                ('param6', models.CharField(blank=True, default='N/A', max_length=200, null=True)),
                ('param7', models.CharField(blank=True, default='N/A', max_length=200, null=True)),
                ('param8', models.CharField(blank=True, default='N/A', max_length=200, null=True)),
                ('param9', models.CharField(blank=True, default='N/A', max_length=200, null=True)),
                ('param10', models.CharField(blank=True, default='N/A', max_length=200, null=True)),
                ('description', models.CharField(default='N/A', help_text='Description of what this parameter set does', max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parameters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
                'ordering': ('matchingKey', 'sequence'),
            },
        ),
    ]
