# Generated by Django 6.0.2 on 2026-04-05 05:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrafficLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("url", models.URLField(max_length=500)),
                ("path", models.CharField(max_length=500)),
                ("headers", models.JSONField(default=dict, help_text="Request headers")),
                ("cookies", models.JSONField(default=dict, help_text="Request cookies")),
                (
                    "query_params",
                    models.JSONField(default=dict, help_text="Query string parameters"),
                ),
                ("body", models.TextField(blank=True, help_text="Request body (POST data)")),
                ("status_code", models.IntegerField()),
                ("response_headers", models.JSONField(default=dict, help_text="Response headers")),
                ("response_body", models.TextField(blank=True, help_text="Response body")),
                (
                    "response_size",
                    models.IntegerField(default=0, help_text="Response size in bytes"),
                ),
                (
                    "endpoint_name",
                    models.CharField(
                        blank=True, help_text="Name of endpoint being debugged", max_length=200
                    ),
                ),
                ("captured_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "duration_ms",
                    models.FloatField(default=0, help_text="Request duration in milliseconds"),
                ),
                (
                    "har_data",
                    models.JSONField(blank=True, help_text="Full HAR format data", null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(fields=["-captured_at"], name="polysniffer_capture_6a0a4e_idx"),
                    models.Index(fields=["url"], name="polysniffer_url_74c0c7_idx"),
                    models.Index(fields=["endpoint_name"], name="polysniffer_endpoin_5270b8_idx"),
                ],
            },
        ),
    ]
