# Generated by Django 5.2.11 on 2026-05-21 22:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0049_alter_passthroughendpoint_bypass_middleware_and_more'),
        ('polysniffer', '0002_trafficlog_capture_source_client_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this network entry was captured')),
                ('entry_type', models.CharField(choices=[('fetch', 'Fetch API'), ('xhr', 'XMLHttpRequest'), ('websocket', 'WebSocket'), ('navigation', 'Navigation'), ('other', 'Other')], db_index=True, help_text='Type of network request (fetch, xhr, websocket, navigation)', max_length=20)),
                ('url', models.URLField(help_text='Full URL of the request', max_length=1000)),
                ('method', models.CharField(default='GET', help_text='HTTP method (GET, POST, PUT, DELETE, etc.)', max_length=10)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP status code (200, 404, 500, etc.)', null=True)),
                ('duration_ms', models.FloatField(default=0, help_text='Request duration in milliseconds')),
                ('request_headers', models.JSONField(blank=True, default=dict, help_text='Request headers as key-value pairs')),
                ('response_headers', models.JSONField(blank=True, default=dict, help_text='Response headers as key-value pairs')),
                ('request_body', models.TextField(blank=True, default='', help_text='Request body content (may be truncated for large payloads)')),
                ('response_body_preview', models.TextField(blank=True, default='', help_text='Preview of response body (truncated to avoid storage bloat)')),
                ('raw_entry', models.JSONField(blank=True, default=dict, help_text='Complete original entry data as captured from browser')),
            ],
            options={
                'verbose_name': 'Traffic Entry',
                'verbose_name_plural': 'Traffic Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Links related requests in a capture session', max_length=64),
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='service',
            field=models.CharField(blank=True, default='', help_text='mattermost, odoo, nextcloud, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='trafficlog',
            name='capture_source',
            field=models.CharField(blank=True, db_index=True, default='', help_text='passthrough = forwarder; browser_extension = extension; native = server middleware', max_length=32),
        ),
        migrations.CreateModel(
            name='TrafficCapture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_name', models.CharField(help_text='e.g. mattermost-native-2026-05-16', max_length=120)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traffic_captures', to='dose.tenant')),
            ],
            options={
                'verbose_name': 'Traffic Capture',
                'verbose_name_plural': 'Traffic Captures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='capture_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='polysniffer.trafficcapture'),
        ),
        migrations.AddIndex(
            model_name='trafficlog',
            index=models.Index(fields=['service', 'capture_source'], name='polysniffer_service_40dc28_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficlog',
            index=models.Index(fields=['capture_session', '-captured_at'], name='polysniffer_capture_e09fbb_idx'),
        ),
        migrations.AddField(
            model_name='trafficentry',
            name='capture',
            field=models.ForeignKey(help_text='The capture session this entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='polysniffer.trafficcapture'),
        ),
        migrations.AddField(
            model_name='trafficentry',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this traffic entry', on_delete=django.db.models.deletion.CASCADE, related_name='traffic_entries', to='dose.tenant'),
        ),
        migrations.AddIndex(
            model_name='trafficentry',
            index=models.Index(fields=['-timestamp'], name='polysniffer_timesta_238dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficentry',
            index=models.Index(fields=['tenant', '-timestamp'], name='polysniffer_tenant__72ddae_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficentry',
            index=models.Index(fields=['capture', '-timestamp'], name='polysniffer_capture_6480a4_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficentry',
            index=models.Index(fields=['entry_type', '-timestamp'], name='polysniffer_entry_t_163101_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficentry',
            index=models.Index(fields=['tenant', 'capture', '-timestamp'], name='polysniffer_tenant__dc949e_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficentry',
            index=models.Index(fields=['url'], name='polysniffer_url_28e9da_idx'),
        ),
    ]
